averbis/averbis-python-api

README.rst
So far the only link to the readthedocs was in the little "readthedocs" tag on github, which is not that obvious imho.
Hence, the added section. It also contains a little teaser to the example notebooks, which are to come. Here we could also add a link to the google colab notebook in the future, which should come together with the example jupyter notebooks.
=> Adds a documentation section to the readme

averbis/core/_rest_client.py
Referring to our discussion in #8, I feel like the cleanest solution is to keep language as an kwarg with default value None.
I would rather choose None instead of "Auto", since the value "Auto" may suggest that we can detect languages automatically in every pipeline. None just omits the request parameter, which is a sensible choice imho.
Having it as an arg would raise awareness, but would be awkward when interacting with pipelines that only use one language and should not receive any language parameter.
But I'm open to alternatives, ofc.
I feel like the most useful place for documenting possible parameter values is in the documentation of the pipelines or annotators (same goes for the documentation of possible annotationTypes).
I wasn't sure how to unit test this with a mock, if at all. …
=> Issue #8: Change language default value to None

averbis/core/_rest_client.py
- Adds support for the experimental support for obtaining pipelines results as an UIMA CAS
- Adds an optional runtime dependency on DKPro Cassis - the import is only triggered if the experimental API calls are triggered
-
=> #9: Experimental support for obtaining an analysed text as a UIMA CAS

averbis/core/_rest_client.py
- Added `@wraps` decorator to expose the docstring of the wrapped method to the help generator
=> #17 - Documentation for get_type_system and analyse_text_to_cas not generated

averbis/core/_rest_client.py, tests/fixtures.py, tests/test_client.py, tests/test_pipeline.py, tests/test_project.py
- Introduced new variable spec_version in Client that holds information about the current platform version (e.g. "5.33.0" or "6.0.0")
- Added new fixtures that can be used to create a client based on version 5.33.0 or based on version 6.0.0 or based on both. 
- Moved client fixtures in and constants (URLs) in tests to fixtures.py
- Rest Client change #1: Setting pipeline name parameter based on schemaVersion
- Rest Client change #2: Getting number of instances based on platform version
- Added tests for both client changes
- (Other) Small code fixes regarding _verify_ssl and _api_token in Client
- (Other) Renamed unused parameters to "_" such that there are no warnings in tests
=> Issue #19: Configuration Schema 2.0 Support

averbis/core/_rest_client.py, tests/test_client.py
The Client is not robust against a trailing slash in the URL. The double slash leads to a 500 exception (which of cause should not happen by the platform but still this error can be prevented).
=> Feature/robust URLs

averbis/core/_rest_client.py, tests/test_pipeline.py
- Adding new client-level functions get_build_info() and get_spec_version() which access private Client variables. 
- moved build_info() call out of Client constructor to enable waiting for server
- _build_info is cached.
=> Issue 58: Moving built info out of constructor

averbis/core/_rest_client.py, tests/test_process.py
- Use the new endpoint for obtaining a type system specifically for one result
- Rename internal some method to align with endpoint names
=> Issue #63: Use results type system instead of obtaining one from the pipeline

averbis/core/_rest_client.py, docs/api.rst, docs/conf.py
* New timeout parameter and Client level and for some selected endpoints: Specifying the timeout for a selected endpoint prevails over the Client level timeout
* No tests were added; tested timeout parameter manually with a real Heath Discovery instance
* Added documentation for Client constructor, fixed sphinx config (removed specification for classes that do not exist anymore, `__init__` is documented only for Client)
* Fixed copyright year
=> Issue #62: Allow setting timeout on Client level and for selected endpoints

setup.py
- Set minimum cassis version to 0.6.0
=> #89 - Upgrade to DKPro Cassis 0.6.0

averbis/core/_rest_client.py, tests/fixtures.py, tests/test_process.py
- adding page and page_size as parameters to export_text_analysis
- some documentation
- added unit test (but also tested it in live product, see comment: https://github.com/averbis/averbis-python-api/issues/98#issuecomment-988057715)
=> Issue #98: Adding `page` and `page_size` parameter to export_text_analysis

averbis/core/_rest_client.py
- Instead of returning the iterator/generator produced by `executor.map`, yield the results individually. This seems to achieve the desired effect
=> Issue #101: analyse_texts returns results only after all data has been processed

averbis/core/_rest_client.py
- Require `filename` parameter when providing a string in import_documents()
- Test manually against an existing HD platform
- closes #118
=> Issue #118: Require filename to be provided in import_documents for str

averbis/core/_rest_client.py, tests/test_process.py
- Added support for POST request to rename process. 
- Fixed lint errors caused by new mypy version setting `no_implicit_optional = True` by default.
- Create a process in the product
- Get the process from the document collection
- Call `process.rename(NEW_PROCESS_NAME)`
Check that the process was renamed in the product and the returned process' name was changed
=> Issue #127: rename process

.github/workflows/run_tests.yml, setup.py
- Run tests against Python 3.9, 3.10 and 3.11
- Adapted package tags
- Building against Ubuntu 20.04 as ubuntu-latest is currently being migrated to ubuntu-22 and is still unstable (https://github.com/actions/setup-python/issues/555)
=> Issue #129: Run tests against all Python versions 3.6 - 3.11.

averbis/core/_rest_client.py, tests/fixtures.py, tests/test_pipeline.py, tests/test_process.py
**What's in the MR?**
- get typesystem of a document text analysis result by document name instead of identifier
- still allow getting by document identifier
=> Issue #141: Get document typesystem by name instead of id

averbis/core/_rest_client.py, tests/fixtures.py, tests/test_process.py
Support optional parameter in `export_text_analysis_to_cas`to limit the export to specific annotation types. 
- Export the textanalysis result of a specific collection, process and document as CAS with `export_text_analysis_to_cas` and specifiy the annotation type(s) you would like to export.
- Check that only those types were exported.
- Check that export without this parameter still works.
=> Issue #133: Support type filter for exporting as CAS

averbis/core/_rest_client.py, tests/test_process.py
* Don't retrieve process details (slow!), just the list of existing processes when checking that the evaluation process has been created
* This is a workaround for a HD bug that occurs in combination of listing all processes and deleted processes
=> Issue #154: Evaluation fails when calling _ensure_process_created

.github/workflows/run_tests.yml, .gitignore, Makefile, averbis/core/_rest_client.py, setup.py
- Adjusted Github workflow to test with python 3.12 & drop tests for Python 3.6, Python 3.7
- Increased minimum Python requirements to 3.8
- Fixed some header & unused imports in setup.py
=> Issue #159: Support for Python 3.12+ & Drop Support for Python 3.6 & Python 3.7

averbis/core/_rest_client.py, tests/test_document_collection.py
Added support for document deletion.
**How to test manually?**
- Run code similar to:
`document_collection.delete_document("test.txt")`
- Check that document was deleted with `document_collection.list_documents()`
=> Issue #158: Add support for document deletion endpoint

averbis/core/_rest_client.py, tests/test_client.py
Added support for license upload.
**How to test manually?**
Test uploading license with:
```
client = Client('url', username='name', password='password')
license_path = Path("my_license.lic")
client.upload_license(license_path)
```
=> Issue #161: Add endpoint for uploading license file

averbis/__init__.py, averbis/core/__init__.py, averbis/core/_rest_client.py, tests/test_client.py, tests/test_pipeline.py, tests/test_project.py, tests/test_resource_container.py
- resource methods on client, project, pipeline level
- resourcecontainer for specific resource interactions and container export
- deprecated old resource api methods
- contains unit tests
**How to test manually?**
Example usage:
```
resource_container_file_path = Path("data") / "test_resource.zip"
hd_client = Client(PRODUCT_URL, api_token=API_TOKEN)
project = hd_client.get_project(PROJECT_NAME)
pipeline = project.get_pipeline(PIPELINE_NAME)
test_resource = pipeline.create_resource_container("test-resource", resource_container_file_path)
print(f"Containers: {[c.name for c in pipeline.list_resource_containers()]}")
print(f"Resources in {test_resource}: {test_resource.list_resources()}")
test_resource.export_resources(target_path) …
```
=> Issue #164: Support new resource API

.github/workflows/run_tests.yml
- Update GitHub Actions workflow to trigger on main and release branches, including PRs
- Add concurrency control and explicit permissions to workflow
- Pin action versions for checkout, setup-python, and codecov
- Improve workflow readability and maintainability
- Restrict Codecov upload to push events only.
* Check if the workflows work
**Automatic testing**
**Documentation**
=> Branch and Path Triggers Updated:

averbis/core/_rest_client.py, tests/fixtures.py, tests/test_pipeline.py
- support fhir format and update other supported formats for the analyse_text endpoint
**How to test manually?**
E..g analyse text and return fhir:
```
hd_client = Client(url, api_token=API_TOKEN)
project = hd_client.create_project(project_name, exist_ok=True)
pipeline = project.get_pipeline(pipeline_name)
pipeline.analyse_text_to_fhir(source="The patient has a fever.")
```
=> Issue #166: Enable FHIR response for analyze_text endpoint

averbis/__init__.py, averbis/core/__init__.py
- make textanalysis mode enum accessible
* test an import with textanalysis mode after installing the python client with e.g.
```
from averbis import TextanalysisMode
...
collection.import_documents(doc_path, textanalysis_mode=TextanalysisMode.REMOVE_RESULTS)
```
=> Issue 203: Export enum TextanalysisMode

.github/workflows/python-ci-build.yml, pyproject.toml, uv.lock
- Remove version limitation for dkpro-cassis
- Remove Python 3.8 from the build list
- Add Python 3.13 instead
- Set minimum version to 3.9.0
* No specific test procedure
**Automatic testing**
**Documentation**
=> Issue #201: Bump minimal Python version to 3.9

averbis/core/_rest_client.py, tests/test_document_collection.py
* Added option to make processes searchable to process creation methods
* create a process with the option enabled and check if the textanalysis results can be searched
**Automatic testing**
=> Issue #210: Mark processes for search
