averbis/platform.py

Issue #2: state not defined

---

README.rst

Hej @reckart, I added some usage information.

Issue #4: adding basic usage information

---

averbis/core/_rest_client.py
tests/test_client.py

- Add support for listing projects (experimental)
- Added unit test
- Add missing experimental API warnings

Issue #29: Listing projects

---

averbis/core/_rest_client.py
tests/test_client.py
tests/test_document_collection.py

- Change source parameter of import_document
- Smart handling of mime_type and filename

Issue #31 - Allow more source options for import_document

---

averbis/core/_rest_client.py

- Changed URLs to the new endpoint names

Issue #33: Adjust endpoint names

---

README.rst

- Add description of how to use the profile file

Issue #25: Add instructions on how to use the client-settigs.json

---

CONTRIBUTING.md

Issue #43 - Add contribution guidelines

---

averbis/core/_rest_client.py

- changed returned Key from create terminology

Issue #42 - Create Terminology dropy KeyError bugfix

---

averbis/core/_rest_client.py
setup.py
tests/test_client.py
tests/test_process.py

* updating ProcessState init to handle the new payload
* adding todo's for after v6 release

Issue #46: Adapt to Process API changes

---

averbis/core/_rest_client.py
tests/test_client.py

- Add exists_project method and corresponding test

#49 - Simple method to check if a project exists

---

averbis/core/_rest_client.py
tests/test_client.py
tests/test_project.py

- Added logic to deal with all three cases of errors (see description in Issue #60) especially now dealing with the case that `raw_response.json()` is not valid json and also printing `status_code` for all Exceptions now
- Added test cases for different error scenarios

Issue #60: Improving error messages

---

.gitignore
averbis/core/_rest_client.py
tests/test_client.py
tests/test_document_collection.py

Closes #68 
Careful. This PR is based on #67 so first merge #67 and then this one.

document collection list processes

---

averbis/core/_rest_client.py

See https://github.com/averbis/averbis-python-api/issues/8#issuecomment-887370212

Issue #8: Removing default language parameter

---

averbis/core/_rest_client.py

* Replaced '**kwargs' arguments by explicit parameter names
* Added explanation for parameters

Issue 80 - Expose top level parameters

---

averbis/core/_rest_client.py
tests/fixtures.py
tests/test_client.py
tests/test_document_collection.py
tests/test_pear.py
tests/test_pipeline.py
tests/test_process.py
tests/test_project.py

- Enabled endpoint for platform 6.x onwards to delete projects
- Added unit tests (also tested on snapshot build)
Additional: Refactored tests to have unique project name

Issue #80: Deleting projects

---

averbis/core/_rest_client.py
tests/test_project.py

- Added Project.list_pipelines()
- Added Project.exists_pipeline(name)
- Added tests for both

Issue #52: Allow listing pipelines

---

averbis/core/_rest_client.py
tests/test_process.py

#91 - Exporting type systems of text analysis results does not work

---

setup.py

- Set minimum cassis version to 0.6.1

#89 - Upgrade to DKPro Cassis 0.6.1

---

averbis/core/_rest_client.py
tests/test_client.py

#96: Properly encoding special chars in URL

---

averbis/core/_rest_client.py

#100 - Remove annotation_types from analyse_text_to_cas as platform does not support this parameter

---

setup.py

- Set minimum cassis version to 0.7.0

#108 - Update to cassis 0.7.0

---

averbis/core/_rest_client.py
docs/api.rst

**In this PR:**
- make process type enum super secret
- re-factor _import_documents to re-use method for cas related requests
- move info on supported cas file formats into documentation

Feature/105 Issue 103 clean up

---

averbis/core/_rest_client.py
setup.py
tests/test_client.py
tests/test_pipeline.py

- Added support for the casToCas endpoint including a basic test

Issue #110: Add support for the analyzeCasToCas endpoint

---

.github/ISSUE_TEMPLATE/release.md
.gitignore
averbis/core/_rest_client.py
setup.py
tests/test_client.py
tests/test_pipeline.py

* Added support for the casToCas endpoint including a basic test
Was: https://github.com/averbis/averbis-python-api/pull/112

Issue #110: Add support for the analyzeCasToCas endpoint #112

---

averbis/core/_rest_client.py
tests/test_client.py
tests/test_process.py

Added flag `exist_ok` to `create_project` and test.

123 add flag exist ok when creating project

---

averbis/core/_rest_client.py
tests/test_process.py

- provide typesystem as optional argument to the `export_text_analysis_to_cas` method
- unit test

Issue #131: Speed up exporting processes via export document

---

averbis/core/_rest_client.py
docs/api.rst

Added a section about the evaluation method to the API reference.
Build the documentation via `make html`in the docs folder and have a look at the new section *Evaluation process*

Issue #137: Document evaluation API endpoint

---

averbis/core/_rest_client.py
tests/test_client.py

- Supporting lists in addition to str in annotation_types parameter
- Internally converting it to str
- Small test of normalization

Issue #149: Support for lists in annotation types parameter

---

averbis/core/_rest_client.py
tests/resources/json/metadata-example.json
tests/test_document_collection.py

- allowed json import into document collection
- described necessary fields for json-import

Issue #174: Support document import in json format

---

averbis/core/_rest_client.py
tests/test_process.py

- additional parameter document_names for exporting textanalysis results to export only some documents 
* pass a list of document names to the export_textanalysis method
* check that only those documents' textanalysis results are exported
**Automatic testing**

Issue 204: Export selected documents' textanalysis results
